### ISSUE TITLE
Crash when opening project Godot 4RC2, Pop!OS Linux

### ISSUE THREAD

**Issue by QueenOfSquiggles** [eumario/godot-manager#59] opened 2023-02-20 21:26 UTC
**Describe the bug**
When attempting to open a project with the launcher, the window disappears and the log file is full of errors.

**To Reproduce**
1. Install Godot 4 RC 2 Mono
2. Import an existing Godot 4 RC 2 Mono project
3. Attempt to open aforementioned project

**Expected behavior**
The launcher opens the Godot executable targeting the particular project path

**Complete the Following:**
 - OS: Linux -  Pop!_OS 22.04 LTS
 - Version: 0.2.1-release

**Additional context**
Applicable log file is attached

[godot_2023-02-20_15.24.56.log](https://github.com/eumario/godot-manager/files/10787861/godot_2023-02-20_15.24.56.log)

**Comment by QueenOfSquiggles** [comment] 2023-02-20 21:33
I generated an additional log file, same testing process, but it the manager was launched with `--verbose` to give more detailed information. I hope it helps!
[godot.log](https://github.com/eumario/godot-manager/files/10787913/godot.log)

**Comment by eumario** [comment] 2023-03-02 09:03
Most of these errors, will happen no matter what, cause of the were it crashes, and what is happening.  The only thing I can suggest, is to try and remove the files in %APPDATA%\Godot-Manager on Windows or ~/.local/share/Godot-Manager on Linux / Mac OS.  I am currently in the middle of a complete Re-Write of the code base, that will be doing a lot of things differently, that may solve a lot of these issues.

**Comment by eumario** [comment] 2023-11-16 07:05
Debug log does not generate enough information to show how this is failing to launch.  Closing as unable to reproduce.

**Closed by eumario** 2023-11-16 07:05 UTC
Labels: noconfirm
