### ISSUE TITLE
Version 0.2.0 for Mac won't run

### ISSUE THREAD

**Issue by Matroc** [eumario/godot-manager#44] opened 2022-10-10 19:25 UTC
**Describe the bug**
When Trying to start version 0.2.0 an my M1 Mac it comes up with a Message 'The application "Godot Manager" can't be opened'

**To Reproduce**
1. Download Godot Manager 0.2.0 to the Applications folder
2. Fix Permissions with: xattr -cr "/Applications/Godot Manager.app/"
3. Click on Godot Manager.app

**Expected behavior**
Godot Manager launches

**Complete the Following:**
 - OS: Mac OS Monterey
 - Version 12.5.1
 - Running on M1 Macbook air

**Additional context**
Version 0.1.3 works fine

**Comment by eumario** [comment] 2022-10-10 20:58
The issue that you are running across, is a known issue even amongst Regular Godot Engine.  Godot Manager is Ad-Hoc signed.  Meaning you have to open it in a specific way in order to allow it to launch.  The reason why xattr -cr "/Applications/Godot Manager.app/" is not working, is cause it is invalidating the Ad-Hoc signature on the Application, causing it to fail.  Unfortunately, I don't have the money to get a Developer License in which to be able to sign the package directly.  You should be able to run the application, by right clicking on the Application Icon (Or Shift Click the Application) to cause the Content Menu to appear, and Select Open from the menu.  This will still give you a Security Error, saying that the Application is not validly signed, but that you can go into Security Preferences in the Control Panel, and click the Allow to Run option for Godot Manager, and it should open up.

**Comment by Matroc** [comment] 2022-10-10 21:10
Yeah, I know that problem. Sadly that is not the issue here.
It still will not run, using the finder context menu->run. It makes no difference at all. And as I said v0.1.3 works absolutely fine this way. But there seems to be something wrong with the 0.2.0 build. Maybe something went wrong during the build that was uploaded to github/itch.io?

I built the latest master myself (and after fixing a version problem with System.IO.Compression) that one actually runs. 
My self built version however crashes when starting projects, so It's not too much of an improvement sadly.

**Comment by eumario** [comment] 2022-10-11 01:14
Latest Master will not be a stable branch, as I have started work on fixing bugs in that build.  Could you try to use the Tagged 0.2.0 Version, to see if that will work for you or not?

Sadly, I do not have a M1 Mac, I have an old Intel Mac Book Air, that is pretty much stuck on 10.15.7, and will not go beyond this version.  (Mainly cause it's a mid 2012 Model), so I can't do any testing beyond that version.

**Comment by Matroc** [comment] 2022-10-11 06:16
Ok, my crashing problem on the master build was another bug I think, I'll try to reproduce that later today or in the following days.

The 0.2.0 tag still did not build as is for me. Same problem as the master. I'm not that firm on C# dependency management but I fixed it by downgrading System.IO.Compression to version 4.0.0.0, since there seemed to be some kind of version conflict. I attached a [log of the failing build](https://github.com/eumario/godot-manager/files/9751597/log.txt).

However after changing the dependency and exporting it, my build seems to work absolutely fine for me. I'd attach it here but its file size exceeds the maximum for github issue attachments.

**Comment by eumario** [comment] 2022-10-11 07:31
That is weird....  It is looking for version 4.1.2.0 of System.IO.Compression, even though the package reference is set to be version 4.3.0.0......  And it looks to only be happening with System.IO.Compression.FileSystem......  Which in all honesty, that shouldn't be happening at all.

**Comment by eumario** [comment] 2022-11-30 04:28
I am closing this, as I am unable to reproduce the bug on my Mac Book to confirm the issue.  Godot Manager v0.3.0, will be using a different library for handling compression, and decompression of Zip files for various things within Godot Manager, and will be re-written under Godot 4, to provide better handling of things, that currently can't be supported on 3.5 version of Godot.

**Closed by eumario** 2022-11-30 04:28 UTC
Labels: Unable To Fix, noconfirm
