### ISSUE TITLE
Desktop entry not created

### ISSUE THREAD

**Issue by cromerc** [eumario/godot-manager#40] opened 2022-10-08 04:30 UTC
**Describe the bug**
I chose to create a desktop entry during the first run wizard and it did not create it. I did not choose to create one for all users, only my current user. I would like to also recommend adding the option to install the .desktop file again in the settings of Godot Manager, that way at any time the user can install it, not just during the first run.

**To Reproduce**
1. First run
2. Choose create desktop entry
3. It is not in my menu.

**Expected behavior**
I expected a desktop icon in my menu.

**Screenshots**
None.

**Complete the Following:**
 - OS: Linux
 - Version 0.2.0

**Additional context**
None.

**Comment by eumario** [comment] 2022-10-08 05:05
Can you confirm that the Desktop file exists in ~/.local/share/applications folder?  When not using System Wide install, that should be where it is installed to.  Also could you verify that you have xdg-desktop-menu available on your system?  It should be a part of xdg-tools

**Comment by cromerc** [comment] 2022-10-08 05:07
Nope, the desktop file is not there and yes I do have xdg-desktop-menu.

**Comment by cromerc** [comment] 2022-10-08 05:16
I just just checked, and ~/.local/share/icons/hicolor/64x64/apps/godot-manager.png was not created either.

**Comment by eumario** [comment] 2022-10-08 05:20
That should be changed.  It should be looking to the folder you have Godot Manager installed to, for godot-manager.svg

**Comment by eumario** [comment] 2022-10-08 05:25
And it does need to be in a Directory that Godot Manager can write to, either by User or Group Permission.

**Comment by cromerc** [comment] 2022-10-08 05:31
> That should be changed.  It should be looking to the folder you have Godot Manager installed to, for godot-manager.svg

My bad, was looking at commit ca8340f when you added desktop file support.

However, there is not a godot-manager.svg where my godot manager is installed either... And there isn't one in the 0.2.0 linux zip I downloaded.

**Comment by cromerc** [comment] 2022-10-08 05:32
> And it does need to be in a Directory that Godot Manager can write to, either by User or Group Permission.

I have it installed in ~/bin which is user writable.

**Comment by eumario** [comment] 2022-10-08 05:43
The SVG file is created when the Desktop Entry is written.  I have it stored as a resource in the pak that gets attached to the Godot template, so it wouldn't be there, till you actually created a Desktop entry, which only happens on Linux platforms.  If you could try for me, temporarily Rename your Godot-Manager folder in ~/.local/share/Godot-Manager to something like Godot-Manager.bak, and re-launch the Godot Manager app from console, to see what output is generated, and paste what is generated in the console.

**Comment by cromerc** [comment] 2022-10-08 21:12
Just gave that a try. It created both the icon and the desktop entry this time.

However there were 3 errors while running the first run:
```
ERROR: Attempted to convert an unmarshallable managed type to Variant. Name: 'Task`1' Encoding: 21.
   at: mono_object_to_variant_impl (modules/mono/mono_gd/gd_mono_marshal.cpp:1124)
ERROR: Index p_current = 5 is out of bounds (get_tab_count() = 5).
   at: set_current_tab (scene/gui/tab_container.cpp:593)
ERROR: Condition "status != STATUS_BODY" is true. Returned: PoolByteArray()
```

Not sure why it worked this time but not the previous time.

**Comment by eumario** [comment] 2022-10-08 23:43
The First one, is going to be a given, as I'm using an async method, and System.Threading.Task is cannot be Marshalled to Godot.

Second One is a known issue, with the First Run Wizard, it's not a critical error, as it's attempting to switch beyond the number of pages there are in the wizard dialog, but is closed at that point anyways.

Third error, is a Condition status with Networking, something failed, but didn't completely crash out, so it's also not a critical error.

First one will be unchangeable, as using Async methods, with Signal Handlers will never fully work, but it will never crash the program, as I'm not looking for any returns, and Godot doesn't accept any return values, just the Glue between C# and Godot.  Hopefully, with the 0.3.0 Re-write to Godot 4.0, that will be better handled.

Second one, I just need to refactor the code that handles validating when to step to the next step, and validate that it doesn't go out of bounds, which is basically all it is.  But as I said, it isn't going to crash the program, as the wizard is closing anyway at that point.

Third one will definitely benefit from the 0.3.0 Re-write, as I will be moving away from Godot's Networking Stack, and moving to C#/Dotnet's Networking stack, and resolve the hoops that I have to jump through to get things to work.

**Comment by cromerc** [comment] 2022-10-09 02:07
So none of the errors are related to this problem. I wasn't able to replicate it, so no idea why it failed the first time.

**Comment by eumario** [comment] 2022-11-16 05:40
Since I'm not able to reproduce this, I am setting up an alternative, that will create the Shortcut in Settings panel, making it easier to create it, if for some reason First Run Wizard fails to create the Shortcut.

**Closed by eumario** 2022-11-16 05:40 UTC
Labels: bug, question
