### ISSUE TITLE
Tuxfamily mirror option only available during initial setup.

### ISSUE THREAD

**Issue by addmix** [eumario/godot-manager#47] opened 2022-11-06 04:19 UTC
**Describe the bug**
Tuxfamily mirror option present in initial setup version menu, but not the regular version menu, menu options for alphas, betas, and RCs cannot be used, and non-release versions are not available for download.

**Complete the Following:**
 - OS: Windows
 - Version 0.2.0

**Comment by eumario** [comment] 2022-11-06 04:24
This is weird, as it should be present in the top right hand corner of the window....

![image](https://user-images.githubusercontent.com/63555/200154091-c9afa2aa-5c5c-44b4-848a-64e56fdc3d5b.png)

And you are not seeing this?

**Comment by addmix** [comment] 2022-11-06 05:22
Weird, only after a restart of my PC did it display properly. As a side note, none of the images for asset in the asset browser, nor the pictures of the news section were visible, but they are after a windows restart.

**Comment by eumario** [comment] 2022-11-06 05:34
That is weird.  There shouldn't be any issues that would cause The Mirrors or Tags to not show up, as they are always on, even though I use the same panel in the Initial setup panel, as I do in the Main App, the only thing that isn't setup to be visible, is the header, or the Buttons for Add Custom Engine, Download from Webite, and Check for Updates.  The rest should be visible.  As for the images for Asset Library and News, it downloads them from the website, so it may have been a Network issue, but there really shouldn't be any issues.

**Comment by addmix** [comment] 2022-11-07 01:14
I'll look to reproduce with a 100% clean install.

**Comment by eumario** [comment] 2022-11-30 04:26
Since no further details on this report has come forth, closing this for now.  If a reproducible way is found for this bug to re-emerge, then re-open, and post the details of how you were able to reproduce this issue.

**Closed by eumario** 2022-11-30 04:26 UTC
Labels: Unable To Fix, noconfirm
